# Generated by Django 5.0.3 on 2024-03-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="body",
            new_name="text",
        ),
    ]
